create table if not exists public.card_generation_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  istanbul_day date not null default ((now() at time zone 'Europe/Istanbul')::date)
);

create index if not exists card_generation_logs_user_day_idx
  on public.card_generation_logs (user_id, istanbul_day);

alter table public.card_generation_logs enable row level security;

drop policy if exists "Users can view their own card generation logs"
  on public.card_generation_logs;

create policy "Users can view their own card generation logs"
  on public.card_generation_logs
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert their own card generation logs"
  on public.card_generation_logs;

create policy "Users can insert their own card generation logs"
  on public.card_generation_logs
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);
